Fix exception in 'cvc upload'
At first 'cvc upload' (and 'cvc publish' command also, for that matter) was
bailing out of LocalDataset.upload_image() just with an assert that http status
was not 200, but after switching that to an exception with error details:

  RuntimeError: Upload failed with code 403 message <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we
    calculated does not match the signature you provided. Check your key and
    signing method.</Message>

  << snip more error message >>

It turns out the old cvc.py has a workaround that solves this problem:
disable automatic redirects in requests module and handle one level of redirect
manually.