Fix creating a dataset
Complaint in calling DatasetManager.create() was:
  TypeError: create() missing 1 required positional argument: 'name'

but actually it was the 'conservator' argument that had been skipped.