collections upload: don't throw exception on metadata with missing media
When a metadata file had a media id that couldn't be found in Conservator,
the upload method was printing an error message but then tried to
upload the metadata anyways, causing an exception that aborts
the rest of the collection upload

  File "conservator-cli/FLIR/conservator/managers/__init__.py",
  line 147, in upload
      media.upload_metadata(file_path)
      AttributeError: 'bool' object has no attribute 'upload_metadata

Only attempt the metadata upload if its corresponding media could
actually be found.